[package]
name = "vendec"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
ash = "0.38.0"
env_logger = "0.11.6"
log = "0.4.25"
vulkano = { git = "https://github.com/vulkano-rs/vulkano.git", branch = "master" }

[profile.dev]
opt-level = 1
