[workspace]
resolver = "2"
members = ["crates/libva", "crates/libva-sys", "crates/vendec"]

[workspace.dependencies]
libloading = "0.8"
bitflags = "2.8"
paste = "1"
vendec = { path = "crates/vendec" }
vendec-libva-sys = { path = "crates/libva-sys" }
vendec-libva = { path = "crates/libva" }
